import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import CreativeProducts from '../components/CreativeProducts'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Partners from '../components/Partners'
import Services from '../components/services'
 export default function Home() {
  return (
    <div dir='rtl' style={{ scrollBehavior: 'smooth' }} >
      <Head>
        <title>شركة وادان التجارية</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Services />
      <CreativeProducts />
      {/* <Partners /> */}
      <Contact />
      <Footer />
    </div>
  )
}
